//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeSphere_App.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleDetails
    {
        public int ID { get; set; }
        public Nullable<int> Sale_ID { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public string Quantity { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Sales Sales { get; set; }
    }
}
