//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanalPosMusterileri
    {
        public int ID { get; set; }
        public string FirmaAdi { get; set; }
        public string SaticiKodu { get; set; }
        public string SaticiSifre { get; set; }
        public string WebSitesi { get; set; }
        public Nullable<bool> Durum { get; set; }
    }
}
